
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      CR Input Header      <small><?= cclang('detail', 'CR Input Header'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/manage-form/form_cr_input_header'); ?>">CR Input Header</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">CR Input Header</h3>
                     <h5 class="widget-user-desc">Detail CR Input Header</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_form_cr_input_header" id="form_form_cr_input_header" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Silahkan Upload Foto CR  </label>
                        <div class="col-sm-8">
                             <?php if (is_image($form_cr_input_header->silahkan_upload_foto_cr_)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/form_cr_input_header/' . $form_cr_input_header->silahkan_upload_foto_cr_; ?>">
                                <img src="<?= BASE_URL . 'uploads/form_cr_input_header/' . $form_cr_input_header->silahkan_upload_foto_cr_; ?>" class="image-responsive" alt="image form_cr_input_header" title="Silahkan Upload Foto CR  form_cr_input_header" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/manage-form/file/download/form_cr_input_header/' . $form_cr_input_header->silahkan_upload_foto_cr_; ?>">
                                 <img src="<?= get_icon_file($form_cr_input_header->silahkan_upload_foto_cr_); ?>" class="image-responsive" alt="image form_cr_input_header" title="Silahkan Upload Foto CR  <?= $form_cr_input_header->silahkan_upload_foto_cr_; ?>" width="40px"> 
                               <?= $form_cr_input_header->silahkan_upload_foto_cr_ ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Silahkan Pilih Tanggal CR </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->silahkan_pilih_tanggal_cr); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Pilih Kode Cost Project </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->pilih_kode_cost_project); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Pilih Kode Cost Induk </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->pilih_kode_cost_induk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Pilih Kode Cost Cabang </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->pilih_kode_cost_cabang); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Pilih Kode Cost Ranting </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->pilih_kode_cost_ranting); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Silahkan Isi Uraian CR </label>

                        <div class="col-sm-8">
                           <?= _ent($form_cr_input_header->silahkan_isi_uraian_cr); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('form_cr_input_header_update', function() use ($form_cr_input_header){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="<?= cclang('update', 'form_cr_input_header'); ?> (Ctrl+e)" href="<?= site_url('administrator/manage-form/form_cr_input_header/edit/'.$form_cr_input_header->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', 'Form Cr Input Header'); ?></a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/manage-form/form_cr_input_header/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list', 'Form Cr Input Header'); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
