
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Form Kode Cost CR      <small><?= cclang('detail', 'Form Kode Cost CR'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/manage-form/form_form_kode_cost_cr'); ?>">Form Kode Cost CR</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Form Kode Cost CR</h3>
                     <h5 class="widget-user-desc">Detail Form Kode Cost CR</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_form_form_kode_cost_cr" id="form_form_form_kode_cost_cr" >
                   
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Cost Product </label>

                        <div class="col-sm-8">
                           <?= _ent($form_form_kode_cost_cr->kode_cost_product); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Cost Induk </label>

                        <div class="col-sm-8">
                           <?= _ent($form_form_kode_cost_cr->kode_cost_induk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Cost Cabang </label>

                        <div class="col-sm-8">
                           <?= _ent($form_form_kode_cost_cr->kode_cost_cabang); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Cost Ranting </label>

                        <div class="col-sm-8">
                           <?= _ent($form_form_kode_cost_cr->kode_cost_ranting); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Cost Uraian </label>

                        <div class="col-sm-8">
                           <?= _ent($form_form_kode_cost_cr->kode_cost_uraian); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('form_form_kode_cost_cr_update', function() use ($form_form_kode_cost_cr){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="<?= cclang('update', 'form_form_kode_cost_cr'); ?> (Ctrl+e)" href="<?= site_url('administrator/manage-form/form_form_kode_cost_cr/edit/'.$form_form_kode_cost_cr->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', 'Form Form Kode Cost Cr'); ?></a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/manage-form/form_form_kode_cost_cr/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list', 'Form Form Kode Cost Cr'); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
